### ISSUE TITLE
Is react-native-tab-navigator campatible with react-navigation-redux ?

### ISSUE THREAD

**Issue by mfachmirizal** [openGeeksLab/react-native-tab-navigator#3]
Hello, Im new in react native development, and using the Ignite boilerplate for my work. I want to use this tab navigator with Ignite boilerplate, but had an issue with Ignite pre-generated "NavigationRedux.js". Im just curious, is this possible to use react-native-tab-navigator with Ignite boilerplate ?.
Thanks..

**Comment by openGeeksLab** [comment]
Yes, you can use it with this navigation as a screen in StackNavigator. Also, we recommend using react-navigation with redux instead of react-navigation-redux
