### ISSUE TITLE
how to use with react-navigation?

### ISSUE THREAD

**Issue by hansfpc** [openGeeksLab/react-native-tab-navigator#4]
how to use with react-navigation + nested stack navigators (example)?

**Comment by hansfpc** [comment]
I understand, thank you! 
I'll be waiting

**Comment by mfachmirizal** [comment]
I really need this example,..
thank you

**Comment by Rizwanjamal** [comment]
@openGeeksLab I tried using nested stack navigator with using your tab-navigator .......
Getting difficulties
