### ISSUE TITLE
the tabNavigator doesn't take full width on landscape mode

### ISSUE THREAD

**Issue by BadrAtt** [openGeeksLab/react-native-tab-navigator#5]
when i switch to landscape mode, the tabNavigator keeps the portrait mode width
![screenshot_2018-09-28-16-39-09](https://user-images.githubusercontent.com/38429665/46218687-31c1b580-c33d-11e8-94c7-b4b34a4ea626.png)

**Comment by openGeeksLab** [comment]
@BadrAtt we fixed the issue which you mentioned above. We updated the code, now you can try it.
