### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [openGeeksLab/react-native-tab-navigator#6]
Using react native version 0.57 

![screenshot_20181003-125743](https://user-images.githubusercontent.com/22089729/46390777-145d6480-c70c-11e8-956d-169b3cf9efe2.png)

How to solve this?

**Comment by openGeeksLab** [comment]
fixed! TY. Try again
import { TabNavigation, TabButton, TabIcons } from '**@opengeekslab**/react-native-tab-navigator';
